<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
    <string>she</string>
    <string>sc</string>
  </array>
  <key>name</key>
  <string>She</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>comment</key>
      <string>number</string>
      <key>match</key>
      <string>(?&lt;=\s)\d+</string>
      <key>name</key>
      <string>constant.numeric.source.she</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>character</string>
      <key>match</key>
      <string>#\\\S+</string>
      <key>name</key>
      <string>constant.character.source.she</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>string double quoted</string>
      <key>match</key>
      <string>"([^"]|(\\"))*"</string>
      <key>name</key>
      <string>string.quoted.double.source.she</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>string</string>
      <key>match</key>
      <string>'[^\(\)\s]+</string>
      <key>name</key>
      <string>keyword.operator.source.she</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>string</string>
      <key>match</key>
      <string>#\w+</string>
      <key>name</key>
      <string>keyword.control.source.she</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>function at line start</string>
      <key>match</key>
      <string>^\s*[^\(\)\s]+</string>
      <key>name</key>
      <string>support.function.source.she</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>function in brackets</string>
      <key>match</key>
      <string>(?&lt;=\()[^\(\)\s]+</string>
      <key>name</key>
      <string>support.function.source.she</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>line comment</string>
      <key>match</key>
      <string>;[^
]*</string>
      <key>name</key>
      <string>comment.line.character.source.she</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>comment</string>
      <key>match</key>
      <string>[\)\(]</string>
      <key>name</key>
      <string>constant.language.source.she</string>
    </dict>
  </array>
  <key>scopeName</key>
  <string>source.she</string>
  <key>uuid</key>
  <string>34fc26ad-d8e0-4856-ac1c-c23b22a59671</string>
</dict>
</plist>
